package me.tibetty.sigbrute.decode.emit;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import me.tibetty.sigbrute.decode.DecodedArg;
import org.junit.jupiter.api.Test;

class ConfigEmitterTest {

    @Test
    void emitLeafArg_producesBareBracketList() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("address", "uint160"), null));
        var yaml = ConfigEmitter
            .emit(new byte[]{(byte) 0xaa, (byte) 0xbb, (byte) 0xcc, (byte) 0xdd}, "transfer", args);
        assertTrue(yaml.contains("- [address, uint160]"));
    }

    @Test
    void emitPrimArrayArg_producesDynamicArrayKey() {
        var args = List.<DecodedArg>of(new DecodedArg.PrimArray("[]", List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- \"[]\":"));
        assertTrue(yaml.contains("    - uint256"));
    }

    @Test
    void emitPrimArrayArg_producesFixedArrayKey() {
        var args = List.<DecodedArg>of(new DecodedArg.PrimArray("[3]", List.of("address"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- \"[3]\":"));
    }

    @Test
    void emitTupleArg_producesParenKey() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("", List.of(new DecodedArg.Leaf(List.of("address"), null),
                new DecodedArg.Leaf(List.of("uint256"), null)), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- ():"));
    }

    @Test
    void emitTupleArrayArg_producesQuotedParenArrayKey() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("[]",
            List.of(new DecodedArg.Leaf(List.of("address"), null)), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- \"()[]\":"));
    }

    @Test
    void emitArgComment_renderedAboveArg() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), "some hint"));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("# arg[0]: some hint"));
    }

    @Test
    void emitTupleFieldComment_renderedAboveField() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("",
            List.of(new DecodedArg.Leaf(List.of("bool"), "field hint")), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("# field 0: field hint"));
    }

    @Test
    void emitPrototypeHeader_presentInOutput() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("# Generated by sig-brute decode"));
        assertTrue(yaml.contains("# Recovered prototype"));
    }

    @Test
    void emitNullMethodName_fallsBackToTodoPlaceholder() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, null, args);
        assertTrue(yaml.contains("method_names: [TODO_method_name]"));
    }

    @Test
    void emitBlankMethodName_fallsBackToTodoPlaceholder() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "  ", args);
        assertTrue(yaml.contains("method_names: [TODO_method_name]"));
    }

    @Test
    void emitSelector_hexEncodedWithPrefix() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{(byte) 0xf2, (byte) 0x96, 0x00, 0x01}, "foo",
            args);
        assertTrue(yaml.contains("selector: \"0xf2960001\""));
    }
}
