package me.tibetty.sigbrute.decode.emit;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import me.tibetty.sigbrute.decode.AlternateStructure;
import me.tibetty.sigbrute.decode.DecodedArg;
import me.tibetty.sigbrute.decode.DecodeResult;
import me.tibetty.sigbrute.decode.strategy.DecodeStrategy;
import org.junit.jupiter.api.Test;

class ConfigEmitterTest {

    @Test
    void emitLeafArg_producesBareBracketList() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("address", "uint160"), null));
        var yaml = ConfigEmitter
            .emit(new byte[]{(byte) 0xaa, (byte) 0xbb, (byte) 0xcc, (byte) 0xdd}, "transfer", args);
        assertTrue(yaml.contains("- [address, uint160]"));
    }

    @Test
    void emitPrimArrayArg_producesDynamicArrayKey() {
        var args = List.<DecodedArg>of(new DecodedArg.PrimArray("[]", List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- \"[]\":"));
        assertTrue(yaml.contains("    - uint256"));
    }

    @Test
    void emitPrimArrayArg_producesFixedArrayKey() {
        var args = List.<DecodedArg>of(new DecodedArg.PrimArray("[3]", List.of("address"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- \"[3]\":"));
    }

    @Test
    void emitTupleArg_producesParenKey() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("", List.of(new DecodedArg.Leaf(List.of("address"), null),
                new DecodedArg.Leaf(List.of("uint256"), null)), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- ():"));
    }

    @Test
    void emitTupleArrayArg_producesQuotedParenArrayKey() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("[]",
            List.of(new DecodedArg.Leaf(List.of("address"), null)), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("- \"()[]\":"));
    }

    @Test
    void emitArgComment_renderedAboveArg() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), "some hint"));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("# arg[0]: some hint"));
    }

    @Test
    void emitTupleFieldComment_renderedAboveField() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("",
            List.of(new DecodedArg.Leaf(List.of("bool"), "field hint")), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("# field 0: field hint"));
    }

    @Test
    void emitPrototypeHeader_presentInOutput() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", args);
        assertTrue(yaml.contains("# Generated by sig-brute decode"));
        assertTrue(yaml.contains("# Recovered prototype"));
    }

    @Test
    void emitNullMethodName_fallsBackToTodoPlaceholder() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, null, args);
        assertTrue(yaml.contains("method_names: [TODO_method_name]"));
    }

    @Test
    void emitBlankMethodName_fallsBackToTodoPlaceholder() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "  ", args);
        assertTrue(yaml.contains("method_names: [TODO_method_name]"));
    }

    @Test
    void emitAlternateStructures_rendersCommentedPrototypes() {
        var winner = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var altArgs = List.<DecodedArg>of(
            new DecodedArg.PrimArray("[]", List.of("address"), "alt array"));
        var result = new DecodeResult(winner, List.of(), List.of(new AlternateStructure(altArgs,
            "head:64")), DecodeStrategy.HEURISTIC_SEARCH);
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "foo", result);
        assertTrue(yaml.contains("# Alternate structures"));
        assertTrue(yaml.contains("#   foo(address[])  # head:64"));
    }

    @Test
    void emitSelector_hexEncodedWithPrefix() {
        var args = List.<DecodedArg>of(new DecodedArg.Leaf(List.of("uint256"), null));
        var yaml = ConfigEmitter.emit(new byte[]{(byte) 0xf2, (byte) 0x96, 0x00, 0x01}, "foo",
            args);
        assertTrue(yaml.contains("selector: \"0xf2960001\""));
    }

    @Test
    void emitShallowOpaqueTupleArray_reinfersLeafCandidatesFromComments() {
        var args = List.<DecodedArg>of(new DecodedArg.Tuple("[]",
            List.of(
                new DecodedArg.Leaf(List.of("uint256"),
                    "field 0 — small uint 0x0000000000000000000000000000000000000000000000000000000000000802"),
                new DecodedArg.Leaf(List.of("uint256"),
                    "field 1 — small uint 0x000000000000000000000000000000000000000000000000000000000000119a"),
                new DecodedArg.Leaf(List.of("uint256"),
                    "field 2 — small uint 0x000000000000000000000000000000000000000000000000000000000000227f")),
            null));
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "batchStake", args, List.of("tuple[]"));
        assertTrue(yaml.contains("# arg[0]: opaque tuple[] (shallow skeleton)"));
        assertTrue(yaml.contains("uint16+"), "pinned uint256 from skeleton should widen to calldata heuristics");
        assertFalse(yaml.contains("- [uint256]\n      # field 1"));
    }

    @Test
    void emitShallowOpaqueTuple_keepsSkeletonBytes32InSearchCandidates() {
        var args = List.<DecodedArg>of(
            new DecodedArg.Tuple("",
                List.of(
                    new DecodedArg.Leaf(List.of("bytes32"),
                        "small uint 0x0000000000000000000000000000000000000000000000000000000000000001"),
                    new DecodedArg.Leaf(List.of("uint256"),
                        "small uint 0x00000000000000000000000000000000000000000000000000000000aeecd629")),
                "static opaque tuple, 2 field(s) from inline hints"),
            new DecodedArg.Leaf(List.of("bytes32"),
                "small uint 0x0000000000000000000000000000000000000000000000000000000000000001"),
            new DecodedArg.Leaf(List.of("bytes32"),
                "small uint 0x0000000000000000000000000000000000000000000000000000000000000001"));
        var yaml = ConfigEmitter.emit(new byte[]{0x1f, 0x6d, 0x51, 0x0b}, "sendL2Message", args,
            List.of("tuple", "bytes32", "bytes32"));
        assertTrue(yaml.contains("- [bytes32, uint*, int*"),
            "field 0 must keep bytes32 from skeleton for search");
        assertTrue(yaml.contains("uint32+"), "field 1 still widens uint256 to heuristics");
    }

    @Test
    void emitShallowTopLevel_keepsHeuristicAmbiguityInTupleFields() {
        var args = List.<DecodedArg>of(
            new DecodedArg.Tuple("",
                List.of(new DecodedArg.Leaf(List.of("bytes", "string"), "3 bytes"),
                    new DecodedArg.Leaf(List.of("bytes", "string"), "4 bytes")),
                null),
            new DecodedArg.Leaf(List.of("uint256"), null),
            new DecodedArg.Tuple("",
                List.of(new DecodedArg.PrimArray("[]", List.of("address", "uint*"), "empty array")),
                null));
        var shallow = List.of("tuple", "uint256", "tuple");
        var yaml = ConfigEmitter.emit(new byte[]{0, 0, 0, 1}, "remove_liquidity", args, shallow);
        assertTrue(yaml.contains("# Shallow skeleton:"));
        assertTrue(yaml.contains("#   remove_liquidity(tuple,uint256,tuple)"));
        assertTrue(yaml.contains("- [bytes, string]"));
        assertFalse(yaml.contains("type fixed by skeleton"));
        assertTrue(yaml.contains("- \"[]\":"));
    }
}
