package me.tibetty.sigbrute.decode.emit;

import java.util.List;

import me.tibetty.sigbrute.decode.DecodedArg;
import me.tibetty.sigbrute.util.HexUtil;

/**
 * Renders a decoded calldata as a sig-brute YAML config. Output uses bare-list leaves and the
 * {@code ()} / {@code "()[]"} / {@code "[]"} key forms exactly as the schema and existing examples
 * do.
 */
public final class ConfigEmitter {

    private ConfigEmitter() {
    }

    public static String emit(byte[] selector, String methodName, List<DecodedArg> args) {
        var sb = new StringBuilder();
        sb.append("# Generated by sig-brute decode — review and refine before running.\n");
        sb.append(
            "# Method name is a guess; add alternates to method_names to broaden the search.\n");
        sb.append("# Tighten or loosen the per-arg type candidates based on what you know.\n");
        sb.append("#\n");
        sb.append("# Recovered prototype (first candidate per leaf — wildcards collapsed):\n");
        sb.append("#   ").append(PrototypeRenderer.render(methodName, args)).append('\n');
        sb.append("# The structure (arg count, tuple/array nesting) is exact;\n");
        sb.append("# the per-leaf type is a guess and is what sig-brute will brute-force.\n\n");

        sb.append("selector: \"0x").append(HexUtil.toHex(selector)).append("\"\n");
        var name = (methodName == null || methodName.isBlank()) ? "TODO_method_name" : methodName;
        sb.append("method_names: [").append(name).append("]\n\n");

        sb.append("args:\n");
        for (var i = 0; i < args.size(); i++) {
            var a = args.get(i);
            sb.append("  # arg[").append(i).append("]");
            if (a.comment() != null && !a.comment().isBlank()) {
                sb.append(": ").append(a.comment());
            }
            sb.append('\n');
            emitArg(sb, a, "  ");
            sb.append('\n');
        }
        return sb.toString();
    }

    /**
     * Renders one arg. {@code listEntryPrefix} is the base indent for the "- " bullet (i.e. the
     * indent of the list this arg belongs to).
     */
    private static void emitArg(StringBuilder sb, DecodedArg a, String listEntryPrefix) {
        if (a instanceof DecodedArg.Leaf leaf) {
            sb.append(listEntryPrefix).append("- [").append(joinCandidates(leaf.candidates()))
                .append("]");
            sb.append('\n');
        } else if (a instanceof DecodedArg.PrimArray pa) {
            var keyForm = quoteArrayKey(pa.arraySuffix());
            sb.append(listEntryPrefix).append("- ").append(keyForm).append(":\n");

            var childIndent = listEntryPrefix + "    ";
            for (var c : pa.baseCandidates()) {
                sb.append(childIndent).append("- ").append(c).append('\n');
            }
        } else if (a instanceof DecodedArg.Tuple t) {
            var keyForm = quoteTupleKey(t.arraySuffix());
            sb.append(listEntryPrefix).append("- ").append(keyForm).append(":\n");

            var childIndent = listEntryPrefix + "    ";
            for (var j = 0; j < t.fields().size(); j++) {
                var f = t.fields().get(j);
                if (f.comment() != null && !f.comment().isBlank()) {
                    sb.append(childIndent).append("# field ").append(j).append(": ")
                        .append(f.comment()).append('\n');
                }
                emitArg(sb, f, childIndent);
            }
        }
    }

    private static String joinCandidates(List<String> cands) {
        return String.join(", ", cands);
    }

    /** Returns {@code ()} (unquoted) or {@code "()[]"} / {@code "()[N]"} (quoted). */
    private static String quoteTupleKey(String arraySuffix) {
        if (arraySuffix == null || arraySuffix.isEmpty()) {
            return "()";
        }

        return "\"()" + arraySuffix + "\"";
    }

    /** Returns {@code "[]"} or {@code "[N]"} (always quoted). */
    private static String quoteArrayKey(String arraySuffix) {
        return "\"" + arraySuffix + "\"";
    }
}
