package me.tibetty.sigbrute.decode.emit;

import java.util.List;

import me.tibetty.sigbrute.decode.AlternateStructure;
import me.tibetty.sigbrute.decode.DecodedArg;
import me.tibetty.sigbrute.decode.DecodeResult;
import me.tibetty.sigbrute.decode.ShallowSkeletonHints;
import me.tibetty.sigbrute.decode.strategy.DecodeStrategy;
import me.tibetty.sigbrute.util.HexUtil;

/**
 * Renders a decoded calldata as a sig-brute YAML config. Output uses bare-list leaves and the
 * {@code ()} / {@code "()[]"} / {@code "[]"} key forms exactly as the schema and existing examples
 * do.
 */
public final class ConfigEmitter {

    private ConfigEmitter() {
    }

    public static String emit(byte[] selector, String methodName, DecodeResult result) {
        return emit(selector, methodName, result, List.of());
    }

    public static String emit(byte[] selector, String methodName, DecodeResult result,
        List<String> shallowTopLevelTypes) {
        return emit(selector, methodName, result.args(), result.warnings(),
            result.alternateStructures(), result.strategy().id(), shallowTopLevelTypes);
    }

    public static String emit(byte[] selector, String methodName, List<DecodedArg> args) {
        return emit(selector, methodName, args, List.of());
    }

    public static String emit(byte[] selector, String methodName, List<DecodedArg> args,
        List<String> shallowTopLevelTypes) {
        return emit(selector, methodName, args, List.of(), List.of(), DecodeStrategy.GREEDY.id(),
            shallowTopLevelTypes);
    }

    private static String emit(byte[] selector, String methodName, List<DecodedArg> args,
        List<String> warnings, List<AlternateStructure> alternates,
        String strategyId, List<String> shallowTopLevelTypes) {
        var sb = new StringBuilder();
        var shallow = useShallowEmit(shallowTopLevelTypes, args);
        appendCommentHeader(sb, new EmitHeader(methodName, args, alternates, warnings, strategyId,
            shallow, shallowTopLevelTypes));
        appendYamlBody(sb, selector, methodName, args, shallow, shallowTopLevelTypes);
        return sb.toString();
    }

    private record EmitHeader(
        String methodName,
        List<DecodedArg> args,
        List<AlternateStructure> alternates,
        List<String> warnings,
        String strategyId,
        boolean shallow,
        List<String> shallowTopLevelTypes
    ) {
    }

    private static void appendCommentHeader(StringBuilder sb, EmitHeader header) {
        sb.append("# Generated by sig-brute decode — review and refine before running.\n");
        sb.append(
            "# Method name is a guess; add alternates to method_names to broaden the search.\n");
        sb.append("# Tighten or loosen the per-arg type candidates based on what you know.\n");
        sb.append("#\n");
        if (header.shallow()) {
            sb.append("# Shallow skeleton: top-level inline tuples shown as opaque tuple / tuple[].\n");
            sb.append("# Inner tuple fields use calldata heuristics only — expect [bytes, string], uint*, or [] ambiguities.\n");
        }
        sb.append("# Recovered prototype (first candidate per leaf — wildcards collapsed):\n");
        sb.append("#   ").append(recoveredPrototype(header)).append('\n');
        appendAlternateStructureComments(sb, header.methodName(), header.alternates());
        sb.append("# The structure (arg count, tuple/array nesting) is exact;\n");
        sb.append("# the per-leaf type is a guess and is what sig-brute will brute-force.\n");
        sb.append("# Decode strategy: ").append(header.strategyId()).append('\n');
        for (var warning : header.warnings()) {
            sb.append("# WARNING: ").append(warning).append('\n');
        }
        sb.append('\n');
    }

    private static String recoveredPrototype(EmitHeader header) {
        if (header.shallow()) {
            return PrototypeRenderer.renderFromShallowTypes(header.methodName(), header.shallowTopLevelTypes());
        }
        return PrototypeRenderer.render(header.methodName(), header.args());
    }

    private static void appendAlternateStructureComments(StringBuilder sb, String methodName,
        List<AlternateStructure> alternates) {
        if (alternates.isEmpty()) {
            return;
        }
        sb.append("# Alternate structures (heuristic near-ties — review before search):\n");
        for (var alt : alternates) {
            sb.append("#   ").append(PrototypeRenderer.render(methodName, alt.args()));
            sb.append("  # ").append(alt.tag()).append('\n');
        }
    }

    private static void appendYamlBody(StringBuilder sb, byte[] selector, String methodName,
        List<DecodedArg> args, boolean shallow, List<String> shallowTopLevelTypes) {
        sb.append("selector: \"0x").append(HexUtil.toHex(selector)).append("\"\n");
        var name = (methodName == null || methodName.isBlank()) ? "TODO_method_name" : methodName;
        sb.append("method_names: [").append(name).append("]\n\n");
        sb.append("args:\n");
        for (var i = 0; i < args.size(); i++) {
            emitTopLevelArg(sb, args.get(i), i, shallow, shallowTopLevelTypes);
        }
    }

    private static void emitTopLevelArg(StringBuilder sb, DecodedArg arg, int index, boolean shallow,
        List<String> shallowTopLevelTypes) {
        sb.append("  # arg[").append(index).append("]");
        appendArgComment(sb, arg, index, shallow, shallowTopLevelTypes);
        sb.append('\n');
        if (isOpaqueShallowArg(index, shallow, shallowTopLevelTypes)) {
            emitOpaqueTopLevelTuple(sb, arg, shallowTopLevelTypes.get(index));
        } else {
            emitArg(sb, arg, "  ");
        }
        sb.append('\n');
    }

    private static void appendArgComment(StringBuilder sb, DecodedArg arg, int index, boolean shallow,
        List<String> shallowTopLevelTypes) {
        if (isOpaqueShallowArg(index, shallow, shallowTopLevelTypes)) {
            sb.append(": opaque tuple (shallow skeleton)");
            return;
        }
        if (arg.comment() != null && !arg.comment().isBlank()) {
            sb.append(": ").append(arg.comment());
        }
    }

    private static boolean isOpaqueShallowArg(int index, boolean shallow,
        List<String> shallowTopLevelTypes) {
        return shallow && index < shallowTopLevelTypes.size()
            && ShallowSkeletonHints.isOpaqueTopLevelTupleHint(shallowTopLevelTypes.get(index));
    }

    private static boolean useShallowEmit(List<String> shallowTopLevelTypes, List<DecodedArg> args) {
        return shallowTopLevelTypes != null && !shallowTopLevelTypes.isEmpty()
            && shallowTopLevelTypes.size() == args.size();
    }

    private static void emitOpaqueTopLevelTuple(StringBuilder sb, DecodedArg decoded,
        String shallowType) {
        var suffix = ShallowSkeletonHints.arraySuffixFromShallowType(shallowType);
        var keyForm = quoteTupleKey(suffix);
        sb.append("  - ").append(keyForm).append(':').append('\n');
        var childIndent = "      ";
        if (decoded instanceof DecodedArg.Tuple t) {
            for (var j = 0; j < t.fields().size(); j++) {
                var f = t.fields().get(j);
                if (f.comment() != null && !f.comment().isBlank()) {
                    sb.append(childIndent).append("# field ").append(j).append(": ")
                        .append(f.comment()).append('\n');
                }
                appendShallowEmptyArrayAlternate(sb, f, childIndent);
                emitArg(sb, f, childIndent);
            }
        } else {
            emitArg(sb, decoded, childIndent);
        }
    }

    /** When heuristics pick an empty dynamic array, note the bytes/string encoding alternative. */
    private static void appendShallowEmptyArrayAlternate(StringBuilder sb, DecodedArg field,
        String indent) {
        if (!(field instanceof DecodedArg.PrimArray pa) || !"[]".equals(pa.arraySuffix())) {
            return;
        }
        if (pa.comment() == null || !pa.comment().contains("empty array")) {
            return;
        }
        sb.append(indent).append("#   or [bytes, string] for empty length-prefixed payload\n");
    }

    /**
     * Renders one arg. {@code listEntryPrefix} is the base indent for the "- " bullet (i.e. the
     * indent of the list this arg belongs to).
     */
    private static void emitArg(StringBuilder sb, DecodedArg a, String listEntryPrefix) {
        if (a instanceof DecodedArg.Leaf leaf) {
            sb.append(listEntryPrefix).append("- [").append(joinCandidates(leaf.candidates()))
                .append("]");
            sb.append('\n');
        } else if (a instanceof DecodedArg.PrimArray pa) {
            var keyForm = quoteArrayKey(pa.arraySuffix());
            sb.append(listEntryPrefix).append("- ").append(keyForm).append(":\n");

            var childIndent = listEntryPrefix + "    ";
            for (var c : pa.baseCandidates()) {
                sb.append(childIndent).append("- ").append(c).append('\n');
            }
        } else if (a instanceof DecodedArg.Tuple t) {
            var keyForm = quoteTupleKey(t.arraySuffix());
            sb.append(listEntryPrefix).append("- ").append(keyForm).append(':');
            // For fallback-decoded tuples the structure is ambiguous: a dynamic array (T[])
            // encodes identically at the byte level. Hint the user so they can choose.
            if (t.arraySuffix().isEmpty() && isFallbackComment(t.comment())) {
                sb.append("  # or []: for a dynamic T[]");
            }
            sb.append('\n');

            var childIndent = listEntryPrefix + "    ";
            for (var j = 0; j < t.fields().size(); j++) {
                var f = t.fields().get(j);
                if (f.comment() != null && !f.comment().isBlank()) {
                    sb.append(childIndent).append("# field ").append(j).append(": ")
                        .append(f.comment()).append('\n');
                }
                emitArg(sb, f, childIndent);
            }
        }
    }

    private static String joinCandidates(List<String> cands) {
        return String.join(", ", cands);
    }

    /** {@code true} when the comment originates from the heuristic fallback decode path. */
    private static boolean isFallbackComment(String comment) {
        return comment != null && comment.startsWith("fallback");
    }

    /** Returns {@code ()} (unquoted) or {@code "()[]"} / {@code "()[N]"} (quoted). */
    private static String quoteTupleKey(String arraySuffix) {
        if (arraySuffix == null || arraySuffix.isEmpty()) {
            return "()";
        }

        return "\"()" + arraySuffix + "\"";
    }

    /** Returns {@code "[]"} or {@code "[N]"} (always quoted). */
    private static String quoteArrayKey(String arraySuffix) {
        return "\"" + arraySuffix + "\"";
    }
}
